### ISSUE TITLE
Download expectation failure: HttpExceptionRequest Request

### ISSUE THREAD

**Issue by ZhidongZhang-code** [luispedro/redundant100#1]
I tried to compile the redundant100 and got this error:
`Download expectation failure: HttpExceptionRequest Request `
Could you please help me solve this problem? Thanks a lot!
In addition, here is the complete code for this error:

> (python-3.7) [zhangzhd@vm-login02 redundant100]$ jug-execute jugfile.py
mkdir -p bin
stack install --local-bin-path $PWD/bin
Preparing to install GHC (alpine) to an isolated location.
This will not interfere with any system-level installation.
No sha1 or sha256 found in metadata, download hash won't be checked.
Preparing to download ghc-alpine-8.2.2 ...
Download expectation failure: HttpExceptionRequest Request {
  host                 = "mitchty.net"
  port                 = 443
  secure               = True
  requestHeaders       = [("User-Agent","The Haskell Stack")]
  path                 = "/ghc/8.2.2/ghc-8.2.2-x86_64-alpine-linux.tar.xz"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (StatusCodeException (Response {responseStatus = Status {statusCode = 404, statusMessage = "Not Found"}, responseVersion = HTTP/1.1, responseHeaders = [("Server","nginx"),("Date","Tue, 02 Aug 2022 05:08:42 GMT"),("Content-Type","text/html"),("Content-Length","146"),("Connection","keep-alive")], responseBody = (), responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose}) "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body>\r\n<center>
make: *** [Makefile:3: all] Error 1
CRITICAL:root:Exception while running jugfile.make: Error in system
Traceback (most recent call last):
  File "/public/home/TonyWuLab/zhangzhd/anaconda3/envs/python-3.7/bin/jug-execute", line 8, in <module>
    main(argv)
  File "/public/home/TonyWuLab/zhangzhd/anaconda3/envs/python-3.7/lib/python3.7/site-packages/jug/jug.py", line 258, in main
    retval = cmdapi.run(options.subcommand, options=options, store=store, jugspace=jugspace)
  File "/public/home/TonyWuLab/zhangzhd/anaconda3/envs/python-3.7/lib/python3.7/site-packages/jug/subcommands/__init__.py", line 269, in run
    return cmd(*args, **kwargs)
  File "/public/home/TonyWuLab/zhangzhd/anaconda3/envs/python-3.7/lib/python3.7/site-packages/jug/subcommands/__init__.py", line 159, in __call__
    return self.run(*args, **kwargs)
  File "/public/home/TonyWuLab/zhangzhd/anaconda3/envs/python-3.7/lib/python3.7/site-packages/jug/subcommands/execute.py", line 99, in run
    failures = execution_loop(tasks, options) or failures
  File "/public/home/TonyWuLab/zhangzhd/anaconda3/envs/python-3.7/lib/python3.7/site-packages/jug/jug.py", line 199, in execution_loop
    t.run(debug_mode=options.debug)
  File "/public/home/TonyWuLab/zhangzhd/anaconda3/envs/python-3.7/lib/python3.7/site-packages/jug/task.py", line 117, in run
    self._result = self._execute()
  File "/public/home/TonyWuLab/zhangzhd/anaconda3/envs/python-3.7/lib/python3.7/site-packages/jug/task.py", line 127, in _execute
    return self.f(*args,**kwargs)
  File "jugfile.py", line 31, in make
    jug_execute.f(['make'])
  File "/public/home/TonyWuLab/zhangzhd/anaconda3/envs/python-3.7/lib/python3.7/site-packages/jug/utils.py", line 218, in jug_execute
    raise SystemError("Error in system")
SystemError: Error in system

Thank you again!

**Comment by luispedro** [comment]
I think this is just a network failure that probably is either a bad connection or an intermittent issue. Can you just try again?
